In [5]:
import numpy as np
np.absolute(-3)

np.int64(3)

In [72]:
# 1.a
np.arange(1, 10 + 1, 1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
# 1.b
np.arange(0.5, 5 + 0.25 , 0.25)

array([0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 , 2.75, 3.  ,
       3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 , 4.75, 5.  ])

In [27]:
# 2.a
print(np.zeros(10, dtype=int))



[0 0 0 0 0 0 0 0 0 0]


In [41]:
# 2.b
print(np.zeros((4, 3), dtype=float))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [43]:
# 3.a
print(np.linspace(2, 12, 5, dtype=int))

[ 2  4  7  9 12]


In [42]:
# 3.b
print(np.linspace(3, 9, 4, dtype=int))

[3 5 7 9]


In [60]:
# 4.a
randy = np.random.rand(2, 4) 
print(randy)

[[0.03688695 0.60956433 0.50267902 0.05147875]
 [0.27864646 0.90826589 0.23956189 0.14489487]]


In [64]:
# reshape 1*8
sh = np.random.rand(2, 4) 
np.reshape(sh, (8, 1)) 

array([[0.59089294],
       [0.67756436],
       [0.01658783],
       [0.51209306],
       [0.22649578],
       [0.64517279],
       [0.17436643],
       [0.69093774]])

In [58]:
# 4.b
np.random.randint(10, 21, (3,3))

array([[18, 14, 10],
       [12, 19, 17],
       [20, 15, 17]], dtype=int32)

In [ ]:
#5
# מה יתקבל אם נגריל מספרים אקראים תוך שימוש ב- seed קבוע?
#התוצאות של הגרלת המספרים האקראיים יהיו אותו הדבר בכל פעם שנבצע את אותו הקוד.

#מה היתרון של השימוש ב- seed?
# ברגע שהתוצאות של הגרלת המספרים האקראיים יהיה אותו הדבר בדיוק בכל פעם זה מאפשר לבדוק את הקוד על נתונים אקראיים ולהשוות את התוצאות של מתכנתים אחרים שהקוד תקין.  
